/*
 * JSP generated by Resin-4.0.44 (built Wed, 22 Apr 2015 02:02:11 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _testpage__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = new TagState();

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_state.release();
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=ISO-8859-1");
    com.tonbeller.wcf.utils.IncludeTag _jsp_IncludeTag_0 = null;
    com.tonbeller.jpivot.table.TableComponentTag _jsp_TableComponentTag_1 = null;
    com.tonbeller.jpivot.navigator.NavigatorTag _jsp_NavigatorTag_2 = null;
    com.tonbeller.wcf.form.FormComponentTag _jsp_FormComponentTag_3 = null;
    com.tonbeller.jpivot.print.PrintComponentTag _jsp_PrintComponentTag_4 = null;
    com.tonbeller.jpivot.chart.ChartComponentTag _jsp_ChartComponentTag_5 = null;
    com.tonbeller.wcf.table.TableComponentTag _jsp_TableComponentTag_6 = null;
    com.tonbeller.wcf.toolbar.ToolBarTag _jsp_ToolBarTag_7 = null;
    com.tonbeller.wcf.toolbar.ScriptButtonTag _jsp_ScriptButtonTag_8 = null;
    com.tonbeller.wcf.toolbar.ToolSeparatorTag _jsp_ToolSeparatorTag_9 = null;
    com.tonbeller.wcf.toolbar.ScriptButtonTag _jsp_ScriptButtonTag_10 = null;
    com.tonbeller.wcf.toolbar.ImgButtonTag _jsp_ImgButtonTag_11 = null;
    com.tonbeller.wcf.component.RendererTag _jsp_RendererTag_12 = null;

    out.write(_jsp_string0, 0, _jsp_string0.length);
    _jsp_IncludeTag_0 = _jsp_state.get_jsp_IncludeTag_0(pageContext, _jsp_parent_tag);
    _jsp_IncludeTag_0.doStartTag();
    out.write(_jsp_string1, 0, _jsp_string1.length);
    if (_caucho_expr_0.evalBoolean(_jsp_env)) {
      out.write(_jsp_string2, 0, _jsp_string2.length);
      pageContext.forward("/index.jsp");if (true) return;
      out.write(_jsp_string1, 0, _jsp_string1.length);
    }
    out.write(_jsp_string3, 0, _jsp_string3.length);
    _jsp_TableComponentTag_1 = _jsp_state.get_jsp_TableComponentTag_1(pageContext, _jsp_parent_tag);
    _jsp_TableComponentTag_1.setQuery("#{query01}");
    int _jspEval19 = _jsp_TableComponentTag_1.doStartTag();
    int _jsp_end_20 = _jsp_TableComponentTag_1.doEndTag();
    if (_jsp_end_20 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
      return;
    out.write(_jsp_string1, 0, _jsp_string1.length);
    _jsp_NavigatorTag_2 = _jsp_state.get_jsp_NavigatorTag_2(pageContext, _jsp_parent_tag);
    _jsp_NavigatorTag_2.setQuery("#{query01}");
    int _jspEval23 = _jsp_NavigatorTag_2.doStartTag();
    int _jsp_end_24 = _jsp_NavigatorTag_2.doEndTag();
    if (_jsp_end_24 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
      return;
    out.write(_jsp_string1, 0, _jsp_string1.length);
    _jsp_FormComponentTag_3 = _jsp_state.get_jsp_FormComponentTag_3(pageContext, _jsp_parent_tag);
    _jsp_FormComponentTag_3.setId("mdxedit01");
    _jsp_FormComponentTag_3.setXmlUri("/WEB-INF/jpivot/table/mdxedit.xml");
    _jsp_FormComponentTag_3.setModel("#{query01}");
    int _jspEval27 = _jsp_FormComponentTag_3.doStartTag();
    int _jsp_end_28 = _jsp_FormComponentTag_3.doEndTag();
    if (_jsp_end_28 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
      return;
    out.write(_jsp_string1, 0, _jsp_string1.length);
    _jsp_FormComponentTag_3.setId("sortform01");
    _jsp_FormComponentTag_3.setXmlUri("/WEB-INF/jpivot/table/sortform.xml");
    _jsp_FormComponentTag_3.setModel("#{table01}");
    int _jspEval31 = _jsp_FormComponentTag_3.doStartTag();
    int _jsp_end_32 = _jsp_FormComponentTag_3.doEndTag();
    if (_jsp_end_32 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
      return;
    out.write(_jsp_string4, 0, _jsp_string4.length);
    _jsp_PrintComponentTag_4 = _jsp_state.get_jsp_PrintComponentTag_4(pageContext, _jsp_parent_tag);
    int _jspEval35 = _jsp_PrintComponentTag_4.doStartTag();
    int _jsp_end_36 = _jsp_PrintComponentTag_4.doEndTag();
    if (_jsp_end_36 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
      return;
    out.write(_jsp_string1, 0, _jsp_string1.length);
    _jsp_FormComponentTag_3.setId("printform01");
    _jsp_FormComponentTag_3.setXmlUri("/WEB-INF/jpivot/print/printpropertiesform.xml");
    _jsp_FormComponentTag_3.setModel("#{print01}");
    int _jspEval39 = _jsp_FormComponentTag_3.doStartTag();
    int _jsp_end_40 = _jsp_FormComponentTag_3.doEndTag();
    if (_jsp_end_40 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
      return;
    out.write(_jsp_string4, 0, _jsp_string4.length);
    _jsp_ChartComponentTag_5 = _jsp_state.get_jsp_ChartComponentTag_5(pageContext, _jsp_parent_tag);
    _jsp_ChartComponentTag_5.setQuery("#{query01}");
    int _jspEval43 = _jsp_ChartComponentTag_5.doStartTag();
    int _jsp_end_44 = _jsp_ChartComponentTag_5.doEndTag();
    if (_jsp_end_44 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
      return;
    out.write(_jsp_string1, 0, _jsp_string1.length);
    _jsp_FormComponentTag_3.setId("chartform01");
    _jsp_FormComponentTag_3.setXmlUri("/WEB-INF/jpivot/chart/chartpropertiesform.xml");
    _jsp_FormComponentTag_3.setModel("#{chart01}");
    int _jspEval47 = _jsp_FormComponentTag_3.doStartTag();
    int _jsp_end_48 = _jsp_FormComponentTag_3.doEndTag();
    if (_jsp_end_48 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
      return;
    out.write(_jsp_string1, 0, _jsp_string1.length);
    _jsp_TableComponentTag_6 = _jsp_state.get_jsp_TableComponentTag_6(pageContext, _jsp_parent_tag);
    int _jspEval51 = _jsp_TableComponentTag_6.doStartTag();
    int _jsp_end_52 = _jsp_TableComponentTag_6.doEndTag();
    if (_jsp_end_52 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
      return;
    out.write(_jsp_string5, 0, _jsp_string5.length);
    _caucho_expr_1.print(out, _jsp_env, true);
    out.write(_jsp_string6, 0, _jsp_string6.length);
    _jsp_ToolBarTag_7 = _jsp_state.get_jsp_ToolBarTag_7(pageContext, _jsp_parent_tag);
    int _jspEval55 = _jsp_ToolBarTag_7.doStartTag();
    if (_jspEval55 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ScriptButtonTag_8 = _jsp_state.get_jsp_ScriptButtonTag_8(pageContext, _jsp_parent_tag);
      _jsp_ScriptButtonTag_8.setId("cubeNaviButton");
      _jsp_ScriptButtonTag_8.setTooltip("toolb.cube");
      _jsp_ScriptButtonTag_8.setImg("cube");
      _jsp_ScriptButtonTag_8.setModel("#{navi01.visible}");
      _jsp_ScriptButtonTag_8.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ScriptButtonTag_8.setId("mdxEditButton");
      _jsp_ScriptButtonTag_8.setTooltip("toolb.mdx.edit");
      _jsp_ScriptButtonTag_8.setImg("mdx-edit");
      _jsp_ScriptButtonTag_8.setModel("#{mdxedit01.visible}");
      _jsp_ScriptButtonTag_8.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ScriptButtonTag_8.setId("sortConfigButton");
      _jsp_ScriptButtonTag_8.setTooltip("toolb.table.config");
      _jsp_ScriptButtonTag_8.setImg("sort-asc");
      _jsp_ScriptButtonTag_8.setModel("#{sortform01.visible}");
      _jsp_ScriptButtonTag_8.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ToolSeparatorTag_9 = _jsp_state.get_jsp_ToolSeparatorTag_9(pageContext, _jsp_parent_tag);
      _jsp_ToolSeparatorTag_9.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ScriptButtonTag_8.setId("levelStyle");
      _jsp_ScriptButtonTag_8.setTooltip("toolb.level.style");
      _jsp_ScriptButtonTag_8.setImg("level-style");
      _jsp_ScriptButtonTag_8.setModel("#{table01.extensions.axisStyle.levelStyle}");
      _jsp_ScriptButtonTag_8.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ScriptButtonTag_8.setId("hideSpans");
      _jsp_ScriptButtonTag_8.setTooltip("toolb.hide.spans");
      _jsp_ScriptButtonTag_8.setImg("hide-spans");
      _jsp_ScriptButtonTag_8.setModel("#{table01.extensions.axisStyle.hideSpans}");
      _jsp_ScriptButtonTag_8.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ScriptButtonTag_8.setId("propertiesButton");
      _jsp_ScriptButtonTag_8.setTooltip("toolb.properties");
      _jsp_ScriptButtonTag_8.setImg("properties");
      _jsp_ScriptButtonTag_8.setModel("#{table01.rowAxisBuilder.axisConfig.propertyConfig.showProperties}");
      _jsp_ScriptButtonTag_8.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ScriptButtonTag_8.setId("nonEmpty");
      _jsp_ScriptButtonTag_8.setTooltip("toolb.non.empty");
      _jsp_ScriptButtonTag_8.setImg("non-empty");
      _jsp_ScriptButtonTag_8.setModel("#{table01.extensions.nonEmpty.buttonPressed}");
      _jsp_ScriptButtonTag_8.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ScriptButtonTag_8.setId("swapAxes");
      _jsp_ScriptButtonTag_8.setTooltip("toolb.swap.axes");
      _jsp_ScriptButtonTag_8.setImg("swap-axes");
      _jsp_ScriptButtonTag_8.setModel("#{table01.extensions.swapAxes.buttonPressed}");
      _jsp_ScriptButtonTag_8.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ToolSeparatorTag_9.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ScriptButtonTag_10 = _jsp_state.get_jsp_ScriptButtonTag_10(pageContext, _jsp_parent_tag);
      _jsp_ScriptButtonTag_10.setModel("#{table01.extensions.drillMember.enabled}");
      _jsp_ScriptButtonTag_10.setTooltip("toolb.navi.member");
      _jsp_ScriptButtonTag_10.setId("drillMember");
      _jsp_ScriptButtonTag_10.setImg("navi-member");
      _jsp_ScriptButtonTag_10.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ScriptButtonTag_10.setModel("#{table01.extensions.drillPosition.enabled}");
      _jsp_ScriptButtonTag_10.setTooltip("toolb.navi.position");
      _jsp_ScriptButtonTag_10.setId("drillPosition");
      _jsp_ScriptButtonTag_10.setImg("navi-position");
      _jsp_ScriptButtonTag_10.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ScriptButtonTag_10.setModel("#{table01.extensions.drillReplace.enabled}");
      _jsp_ScriptButtonTag_10.setTooltip("toolb.navi.replace");
      _jsp_ScriptButtonTag_10.setId("drillReplace");
      _jsp_ScriptButtonTag_10.setImg("navi-replace");
      _jsp_ScriptButtonTag_10.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ScriptButtonTag_8.setModel("#{table01.extensions.drillThrough.enabled}");
      _jsp_ScriptButtonTag_8.setTooltip("toolb.navi.drillthru");
      _jsp_ScriptButtonTag_8.setId("drillThrough01");
      _jsp_ScriptButtonTag_8.setImg("navi-through");
      _jsp_ScriptButtonTag_8.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ToolSeparatorTag_9.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ScriptButtonTag_8.setId("chartButton01");
      _jsp_ScriptButtonTag_8.setTooltip("toolb.chart");
      _jsp_ScriptButtonTag_8.setImg("chart");
      _jsp_ScriptButtonTag_8.setModel("#{chart01.visible}");
      _jsp_ScriptButtonTag_8.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ScriptButtonTag_8.setId("chartPropertiesButton01");
      _jsp_ScriptButtonTag_8.setTooltip("toolb.chart.config");
      _jsp_ScriptButtonTag_8.setImg("chart-config");
      _jsp_ScriptButtonTag_8.setModel("#{chartform01.visible}");
      _jsp_ScriptButtonTag_8.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ToolSeparatorTag_9.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ScriptButtonTag_8.setId("printPropertiesButton01");
      _jsp_ScriptButtonTag_8.setTooltip("toolb.print.config");
      _jsp_ScriptButtonTag_8.setImg("print-config");
      _jsp_ScriptButtonTag_8.setModel("#{printform01.visible}");
      _jsp_ScriptButtonTag_8.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ImgButtonTag_11 = _jsp_state.get_jsp_ImgButtonTag_11(pageContext, _jsp_parent_tag);
      _jsp_ImgButtonTag_11.setId("printpdf");
      _jsp_ImgButtonTag_11.setTooltip("toolb.print");
      _jsp_ImgButtonTag_11.setImg("print");
      _jsp_ImgButtonTag_11.setHref("./Print?cube=01&type=1");
      _jsp_ImgButtonTag_11.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ImgButtonTag_11.setId("printxls");
      _jsp_ImgButtonTag_11.setTooltip("toolb.excel");
      _jsp_ImgButtonTag_11.setImg("excel");
      _jsp_ImgButtonTag_11.setHref("./Print?cube=01&type=0");
      _jsp_ImgButtonTag_11.doStartTag();
      out.write(_jsp_string1, 0, _jsp_string1.length);
    }
    int _jsp_end_140 = _jsp_ToolBarTag_7.doEndTag();
    if (_jsp_end_140 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
      return;
    out.write(_jsp_string3, 0, _jsp_string3.length);
    _jsp_RendererTag_12 = _jsp_state.get_jsp_RendererTag_12(pageContext, _jsp_parent_tag);
    _jsp_RendererTag_12.setRef("toolbar01");
    _jsp_RendererTag_12.setXslUri("/WEB-INF/jpivot/toolbar/htoolbar.xsl");
    _jsp_RendererTag_12.doStartTag();
    _jsp_RendererTag_12.doEndTag();
    out.write(_jsp_string7, 0, _jsp_string7.length);
    if (_caucho_expr_2.evalBoolean(_jsp_env)) {
      out.write(_jsp_string8, 0, _jsp_string8.length);
    }
    out.write(_jsp_string3, 0, _jsp_string3.length);
    _jsp_RendererTag_12.setRef("navi01");
    _jsp_RendererTag_12.setXslUri("/WEB-INF/jpivot/navi/navigator.xsl");
    _jsp_RendererTag_12.doStartTag();
    _jsp_RendererTag_12.doEndTag();
    out.write(_jsp_string3, 0, _jsp_string3.length);
    if (_caucho_expr_3.evalBoolean(_jsp_env)) {
      out.write(_jsp_string9, 0, _jsp_string9.length);
      _jsp_RendererTag_12 = _jsp_state.get_jsp_RendererTag_12(pageContext, _jsp_parent_tag);
      _jsp_RendererTag_12.setRef("mdxedit01");
      _jsp_RendererTag_12.setXslUri("/WEB-INF/wcf/wcf.xsl");
      _jsp_RendererTag_12.doStartTag();
      _jsp_RendererTag_12.doEndTag();
      out.write(_jsp_string1, 0, _jsp_string1.length);
    }
    out.write(_jsp_string3, 0, _jsp_string3.length);
    _jsp_RendererTag_12.setRef("sortform01");
    _jsp_RendererTag_12.setXslUri("/WEB-INF/wcf/wcf.xsl");
    _jsp_RendererTag_12.doStartTag();
    _jsp_RendererTag_12.doEndTag();
    out.write(_jsp_string3, 0, _jsp_string3.length);
    _jsp_RendererTag_12.setRef("chartform01");
    _jsp_RendererTag_12.setXslUri("/WEB-INF/wcf/wcf.xsl");
    _jsp_RendererTag_12.doStartTag();
    _jsp_RendererTag_12.doEndTag();
    out.write(_jsp_string3, 0, _jsp_string3.length);
    _jsp_RendererTag_12.setRef("printform01");
    _jsp_RendererTag_12.setXslUri("/WEB-INF/wcf/wcf.xsl");
    _jsp_RendererTag_12.doStartTag();
    _jsp_RendererTag_12.doEndTag();
    out.write(_jsp_string10, 0, _jsp_string10.length);
    _jsp_RendererTag_12.setRef("table01");
    _jsp_RendererTag_12.setXslUri("/WEB-INF/jpivot/table/mdxtable.xsl");
    _jsp_RendererTag_12.doStartTag();
    _jsp_RendererTag_12.doEndTag();
    out.write(_jsp_string11, 0, _jsp_string11.length);
    _jsp_RendererTag_12.setRef("table01");
    _jsp_RendererTag_12.setXslUri("/WEB-INF/jpivot/table/mdxslicer.xsl");
    _jsp_RendererTag_12.doStartTag();
    _jsp_RendererTag_12.doEndTag();
    out.write(_jsp_string12, 0, _jsp_string12.length);
    _jsp_RendererTag_12.setRef("query01.drillthroughtable");
    _jsp_RendererTag_12.setXslUri("/WEB-INF/wcf/wcf.xsl");
    _jsp_RendererTag_12.doStartTag();
    _jsp_RendererTag_12.doEndTag();
    out.write(_jsp_string13, 0, _jsp_string13.length);
    _jsp_RendererTag_12.setRef("chart01");
    _jsp_RendererTag_12.setXslUri("/WEB-INF/jpivot/chart/chart.xsl");
    _jsp_RendererTag_12.doStartTag();
    _jsp_RendererTag_12.doEndTag();
    out.write(_jsp_string14, 0, _jsp_string14.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -1650998886690198223L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("testpage.jsp"), -5964742335585614963L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/wcf/wcf-tags.tld"), -2377711429370056142L, false);
    _caucho_depends.add(depend);
    _caucho_depends.add(new com.caucho.make.ClassDependency("com.tonbeller.wcf.utils.IncludeTag", -1773493995146984573L));
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/jpivot/jpivot-tags.tld"), -478640942676185352L, false);
    _caucho_depends.add(depend);
    _caucho_depends.add(new com.caucho.make.ClassDependency("com.tonbeller.jpivot.table.TableComponentTag", -4494208876662755479L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("com.tonbeller.jpivot.navigator.NavigatorTag", 2412088862828393412L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("com.tonbeller.wcf.form.FormComponentTag", -5113855455361217380L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("com.tonbeller.jpivot.print.PrintComponentTag", 7321406512816199068L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("com.tonbeller.jpivot.chart.ChartComponentTag", 4881475464878063337L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("com.tonbeller.wcf.table.TableComponentTag", -839333321613136470L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("com.tonbeller.wcf.toolbar.ScriptButtonTag", 3301644631597893421L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("com.tonbeller.wcf.toolbar.ToolSeparatorTag", -5722443676583564955L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("com.tonbeller.wcf.toolbar.ImgButtonTag", 3257823625718615586L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("com.tonbeller.wcf.toolbar.ToolBarTag", 8753198163623972126L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("com.tonbeller.wcf.component.RendererTag", -3348663073842955080L));
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }

  final static class TagState {
    private com.tonbeller.wcf.utils.IncludeTag _jsp_IncludeTag_0;

    final com.tonbeller.wcf.utils.IncludeTag get_jsp_IncludeTag_0(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_IncludeTag_0 == null) {
        _jsp_IncludeTag_0 = new com.tonbeller.wcf.utils.IncludeTag();
        _jsp_IncludeTag_0.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_IncludeTag_0.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_IncludeTag_0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_IncludeTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_IncludeTag_0.setId("include01");
        _jsp_IncludeTag_0.setHttpParam("query");
        _jsp_IncludeTag_0.setPrefix("/WEB-INF/queries/");
        _jsp_IncludeTag_0.setSuffix(".jsp");
      }

      return _jsp_IncludeTag_0;
    }
    private com.tonbeller.jpivot.table.TableComponentTag _jsp_TableComponentTag_1;

    final com.tonbeller.jpivot.table.TableComponentTag get_jsp_TableComponentTag_1(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_TableComponentTag_1 == null) {
        _jsp_TableComponentTag_1 = new com.tonbeller.jpivot.table.TableComponentTag();
        _jsp_TableComponentTag_1.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_TableComponentTag_1.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_TableComponentTag_1.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_TableComponentTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_TableComponentTag_1.setId("table01");
      }

      return _jsp_TableComponentTag_1;
    }
    private com.tonbeller.jpivot.navigator.NavigatorTag _jsp_NavigatorTag_2;

    final com.tonbeller.jpivot.navigator.NavigatorTag get_jsp_NavigatorTag_2(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_NavigatorTag_2 == null) {
        _jsp_NavigatorTag_2 = new com.tonbeller.jpivot.navigator.NavigatorTag();
        _jsp_NavigatorTag_2.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_NavigatorTag_2.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_NavigatorTag_2.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_NavigatorTag_2.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_NavigatorTag_2.setId("navi01");
        _jsp_NavigatorTag_2.setVisible(false);
      }

      return _jsp_NavigatorTag_2;
    }
    private com.tonbeller.wcf.form.FormComponentTag _jsp_FormComponentTag_3;

    final com.tonbeller.wcf.form.FormComponentTag get_jsp_FormComponentTag_3(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_FormComponentTag_3 == null) {
        _jsp_FormComponentTag_3 = new com.tonbeller.wcf.form.FormComponentTag();
        _jsp_FormComponentTag_3.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_FormComponentTag_3.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_FormComponentTag_3.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_FormComponentTag_3.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_FormComponentTag_3.setVisible(false);
      }

      return _jsp_FormComponentTag_3;
    }
    private com.tonbeller.jpivot.print.PrintComponentTag _jsp_PrintComponentTag_4;

    final com.tonbeller.jpivot.print.PrintComponentTag get_jsp_PrintComponentTag_4(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_PrintComponentTag_4 == null) {
        _jsp_PrintComponentTag_4 = new com.tonbeller.jpivot.print.PrintComponentTag();
        _jsp_PrintComponentTag_4.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_PrintComponentTag_4.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_PrintComponentTag_4.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_PrintComponentTag_4.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_PrintComponentTag_4.setId("print01");
      }

      return _jsp_PrintComponentTag_4;
    }
    private com.tonbeller.jpivot.chart.ChartComponentTag _jsp_ChartComponentTag_5;

    final com.tonbeller.jpivot.chart.ChartComponentTag get_jsp_ChartComponentTag_5(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_ChartComponentTag_5 == null) {
        _jsp_ChartComponentTag_5 = new com.tonbeller.jpivot.chart.ChartComponentTag();
        _jsp_ChartComponentTag_5.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_ChartComponentTag_5.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_ChartComponentTag_5.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_ChartComponentTag_5.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_ChartComponentTag_5.setId("chart01");
        _jsp_ChartComponentTag_5.setVisible(false);
      }

      return _jsp_ChartComponentTag_5;
    }
    private com.tonbeller.wcf.table.TableComponentTag _jsp_TableComponentTag_6;

    final com.tonbeller.wcf.table.TableComponentTag get_jsp_TableComponentTag_6(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_TableComponentTag_6 == null) {
        _jsp_TableComponentTag_6 = new com.tonbeller.wcf.table.TableComponentTag();
        _jsp_TableComponentTag_6.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_TableComponentTag_6.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_TableComponentTag_6.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_TableComponentTag_6.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_TableComponentTag_6.setId("query01.drillthroughtable");
        _jsp_TableComponentTag_6.setVisible(false);
        _jsp_TableComponentTag_6.setSelmode("none");
        _jsp_TableComponentTag_6.setEditable(true);
      }

      return _jsp_TableComponentTag_6;
    }
    private com.tonbeller.wcf.toolbar.ToolBarTag _jsp_ToolBarTag_7;

    final com.tonbeller.wcf.toolbar.ToolBarTag get_jsp_ToolBarTag_7(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_ToolBarTag_7 == null) {
        _jsp_ToolBarTag_7 = new com.tonbeller.wcf.toolbar.ToolBarTag();
        _jsp_ToolBarTag_7.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_ToolBarTag_7.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_ToolBarTag_7.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_ToolBarTag_7.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_ToolBarTag_7.setId("toolbar01");
        _jsp_ToolBarTag_7.setBundle("com.tonbeller.jpivot.toolbar.resources");
      }

      return _jsp_ToolBarTag_7;
    }
    private com.tonbeller.wcf.toolbar.ScriptButtonTag _jsp_ScriptButtonTag_8;

    final com.tonbeller.wcf.toolbar.ScriptButtonTag get_jsp_ScriptButtonTag_8(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_ScriptButtonTag_8 == null) {
        _jsp_ScriptButtonTag_8 = new com.tonbeller.wcf.toolbar.ScriptButtonTag();
        _jsp_ScriptButtonTag_8.setPageContext(pageContext);
        _jsp_ScriptButtonTag_8.setParent((javax.servlet.jsp.tagext.Tag) _jsp_ToolBarTag_7);
      }

      return _jsp_ScriptButtonTag_8;
    }
    private com.tonbeller.wcf.toolbar.ToolSeparatorTag _jsp_ToolSeparatorTag_9;

    final com.tonbeller.wcf.toolbar.ToolSeparatorTag get_jsp_ToolSeparatorTag_9(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_ToolSeparatorTag_9 == null) {
        _jsp_ToolSeparatorTag_9 = new com.tonbeller.wcf.toolbar.ToolSeparatorTag();
        _jsp_ToolSeparatorTag_9.setPageContext(pageContext);
        _jsp_ToolSeparatorTag_9.setParent((javax.servlet.jsp.tagext.Tag) _jsp_ToolBarTag_7);
      }

      return _jsp_ToolSeparatorTag_9;
    }
    private com.tonbeller.wcf.toolbar.ScriptButtonTag _jsp_ScriptButtonTag_10;

    final com.tonbeller.wcf.toolbar.ScriptButtonTag get_jsp_ScriptButtonTag_10(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_ScriptButtonTag_10 == null) {
        _jsp_ScriptButtonTag_10 = new com.tonbeller.wcf.toolbar.ScriptButtonTag();
        _jsp_ScriptButtonTag_10.setPageContext(pageContext);
        _jsp_ScriptButtonTag_10.setParent((javax.servlet.jsp.tagext.Tag) _jsp_ToolBarTag_7);
        _jsp_ScriptButtonTag_10.setRadioGroup("navi");
      }

      return _jsp_ScriptButtonTag_10;
    }
    private com.tonbeller.wcf.toolbar.ImgButtonTag _jsp_ImgButtonTag_11;

    final com.tonbeller.wcf.toolbar.ImgButtonTag get_jsp_ImgButtonTag_11(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_ImgButtonTag_11 == null) {
        _jsp_ImgButtonTag_11 = new com.tonbeller.wcf.toolbar.ImgButtonTag();
        _jsp_ImgButtonTag_11.setPageContext(pageContext);
        _jsp_ImgButtonTag_11.setParent((javax.servlet.jsp.tagext.Tag) _jsp_ToolBarTag_7);
      }

      return _jsp_ImgButtonTag_11;
    }
    private com.tonbeller.wcf.component.RendererTag _jsp_RendererTag_12;

    final com.tonbeller.wcf.component.RendererTag get_jsp_RendererTag_12(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_RendererTag_12 == null) {
        _jsp_RendererTag_12 = new com.tonbeller.wcf.component.RendererTag();
        _jsp_RendererTag_12.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_RendererTag_12.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_RendererTag_12.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_RendererTag_12.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_RendererTag_12.setXslCache(true);
      }

      return _jsp_RendererTag_12;
    }

    void release()
    {
      if (_jsp_IncludeTag_0 != null) {
        _jsp_IncludeTag_0.release();
        _jsp_IncludeTag_0 = null;
      }
      if (_jsp_TableComponentTag_1 != null) {
        _jsp_TableComponentTag_1.release();
        _jsp_TableComponentTag_1 = null;
      }
      if (_jsp_NavigatorTag_2 != null) {
        _jsp_NavigatorTag_2.release();
        _jsp_NavigatorTag_2 = null;
      }
      if (_jsp_FormComponentTag_3 != null) {
        _jsp_FormComponentTag_3.release();
        _jsp_FormComponentTag_3 = null;
      }
      if (_jsp_PrintComponentTag_4 != null) {
        _jsp_PrintComponentTag_4.release();
        _jsp_PrintComponentTag_4 = null;
      }
      if (_jsp_ChartComponentTag_5 != null) {
        _jsp_ChartComponentTag_5.release();
        _jsp_ChartComponentTag_5 = null;
      }
      if (_jsp_TableComponentTag_6 != null) {
        _jsp_TableComponentTag_6.release();
        _jsp_TableComponentTag_6 = null;
      }
      if (_jsp_ToolBarTag_7 != null) {
        _jsp_ToolBarTag_7.release();
        _jsp_ToolBarTag_7 = null;
      }
      if (_jsp_ScriptButtonTag_8 != null) {
        _jsp_ScriptButtonTag_8.release();
        _jsp_ScriptButtonTag_8 = null;
      }
      if (_jsp_ToolSeparatorTag_9 != null) {
        _jsp_ToolSeparatorTag_9.release();
        _jsp_ToolSeparatorTag_9 = null;
      }
      if (_jsp_ScriptButtonTag_10 != null) {
        _jsp_ScriptButtonTag_10.release();
        _jsp_ScriptButtonTag_10 = null;
      }
      if (_jsp_ImgButtonTag_11 != null) {
        _jsp_ImgButtonTag_11.release();
        _jsp_ImgButtonTag_11 = null;
      }
      if (_jsp_RendererTag_12 != null) {
        _jsp_RendererTag_12.release();
        _jsp_RendererTag_12 = null;
      }
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      manager.addTaglibFunctions(_jsp_functionMap, "jp", "http://www.tonbeller.com/jpivot");
      manager.addTaglibFunctions(_jsp_functionMap, "wcf", "http://www.tonbeller.com/wcf");
      manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jstl/core");
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
      _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${query01 == null}");
      _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${title01}");
      _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${query01.result.overflowOccured}");
      _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${mdxedit01.visible}");
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;

  private final static char []_jsp_string14;
  private final static char []_jsp_string10;
  private final static char []_jsp_string2;
  private final static char []_jsp_string11;
  private final static char []_jsp_string6;
  private final static char []_jsp_string9;
  private final static char []_jsp_string8;
  private final static char []_jsp_string12;
  private final static char []_jsp_string3;
  private final static char []_jsp_string0;
  private final static char []_jsp_string13;
  private final static char []_jsp_string1;
  private final static char []_jsp_string7;
  private final static char []_jsp_string5;
  private final static char []_jsp_string4;
  static {
    _jsp_string14 = "\r\n\r\n<p>\r\n\r\n\r\n</form>\r\n\r\n\r\n</body>\r\n</html>\r\n".toCharArray();
    _jsp_string10 = "\r\n\r\n<!-- render the table -->\r\n<p>\r\n".toCharArray();
    _jsp_string2 = "\r\n  ".toCharArray();
    _jsp_string11 = "\r\n<p>\r\nSlicer:\r\n".toCharArray();
    _jsp_string6 = "</h2>\r\n\r\n\r\n".toCharArray();
    _jsp_string9 = "\r\n  <h3>MDX Query Editor</h3>\r\n  ".toCharArray();
    _jsp_string8 = "\r\n  <p>\r\n  <strong style=\"color:red\">Resultset overflow occured</strong>\r\n  <p>\r\n".toCharArray();
    _jsp_string12 = "\r\n\r\n<p>\r\n<!-- drill through table -->\r\n".toCharArray();
    _jsp_string3 = "\r\n\r\n\r\n".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n<html>\r\n<head>\r\n  <title>BIACTA - Multidimensional Analisis Server </title>\r\n  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n  <link rel=\"stylesheet\" type=\"text/css\" href=\"jpivot/table/mdxtable.css\">\r\n  <link rel=\"stylesheet\" type=\"text/css\" href=\"jpivot/navi/mdxnavi.css\">\r\n  <link rel=\"stylesheet\" type=\"text/css\" href=\"wcf/form/xform.css\">\r\n  <link rel=\"stylesheet\" type=\"text/css\" href=\"wcf/table/xtable.css\">\r\n  <link rel=\"stylesheet\" type=\"text/css\" href=\"wcf/tree/xtree.css\">\r\n</head>\r\n<body bgcolor=white>\r\n<form action=\"testpage.jsp\" method=\"post\">\r\n\r\n\r\n".toCharArray();
    _jsp_string13 = "\r\n\r\n<p>\r\n<!-- render chart -->\r\n".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string7 = "\r\n<p>\r\n\r\n\r\n".toCharArray();
    _jsp_string5 = "\r\n\r\n<h2>".toCharArray();
    _jsp_string4 = "\r\n\r\n".toCharArray();
  }
}
